name: Qt6 Windows + Linux Release

on:
  push:
    branches: [ "main" ]
    tags:
      - "v*"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      # Install Qt6
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: "6.6.3"
          host: ${{ runner.os == 'Windows' && 'windows' || 'linux' }}
          target: desktop
          arch: ${{ runner.os == 'Windows' && 'win64_msvc2019_64' || 'gcc_64' }}

      # Linux dependencies
      - name: Install Linux tools
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y ninja-build appimagekit

      - name: Configure
        run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build

      - name: Test
        run: ctest --test-dir build --output-on-failure

      # ----------------------
      # WINDOWS DEPLOY
      # ----------------------
      - name: Deploy Qt (Windows)
        if: runner.os == 'Windows'
        run: |
          windeployqt build\MusicManager.exe --release
          mkdir dist
          xcopy build\* dist\ /E /I

      - name: Archive Windows
        if: runner.os == 'Windows'
        run: |
          powershell Compress-Archive dist MusicManager-windows.zip

      # ----------------------
      # LINUX DEPLOY (AppImage)
      # ----------------------
      - name: Download linuxdeploy
        if: runner.os == 'Linux'
        run: |
          wget -c https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
          chmod +x linuxdeploy-x86_64.AppImage

      - name: Create AppDir
        if: runner.os == 'Linux'
        run: |
          mkdir -p AppDir/usr/bin
          cp build/MusicManager AppDir/usr/bin/

      - name: Build AppImage
        if: runner.os == 'Linux'
        run: |
          ./linuxdeploy-x86_64.AppImage \
            --appdir AppDir \
            --output appimage

      - name: Rename Linux Artifact
        if: runner.os == 'Linux'
        run: mv *.AppImage MusicManager-linux.AppImage

      # Upload artifacts
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}
          path: |
            *.zip
            *.AppImage

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4

      - uses: softprops/action-gh-release@v2
        with:
          files: |
            windows-latest/MusicManager-windows.zip
            ubuntu-latest/MusicManager-linux.AppImage
